apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: example-backendconfig
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2