apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: products
      containers:
      - name: products
        image: lukhee/bg-agric-os:products
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/product
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/product
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
  strategy:
    type: RollingUpdate  # Default strategy, updates pods in a rolling manner
    rollingUpdate:
      maxSurge: 1  # Maximum number of pods that can be created beyond replicas during an update
      maxUnavailable: 1