prometheus:
  prometheusSpec:
    replicas: 2
    retention: "30d"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "2"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
  serviceAccount:
    create: false  # Set to false to use an existing ServiceAccount
    name: prometheus
  prometheusNetworkPolicyEnabled: true
  # nodeExporter:
  #   enabled: false
  alertmanager:
    enabled: true
  server:
    enabled: true
    extraArgs:
      - --web.enable-lifecycle

