# Kustomize build command // kustomize build "folder/dir/kustomization file"
# Kustomize build and apply command // kustomize build "folder/dir/kustomization file" | kubectl apply -f -
# Kustomize edit command using cli // kubectl kustomize edit set image _{_IMAGE_}_=lukhee/bg-agric-os:farming2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - service.yaml

commonLabels:
  org: babban-gona

namespace: production

images:
  - name: _{_IMAGE_}_
    newName: lukhee/bg-agric-os
    newTag: farming

namePrefix: farming-